// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voihhpfkzfpgrvhevycp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaWhocGZremZwZ3J2aGV2eWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Njg0MjMsImV4cCI6MjA2NjU0NDQyM30.tUynLXGWnIow3bwAoYwXBj5IVKFZ8-BC-iITkwJQ1yQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);